travis:
  secure:
    BINSTAR_TOKEN: no2cZZLEc3AdxiL3Dc4v00s1W35kEatxwXqM54QiO+2nPgMSVjGT5oGkEGCLCIAFtflJnlZEC7yQjnCPjJQQyyPYncJS5r2it1aLNXSRyan1CnWsxbuxnLX8Aik+sS3LdrGJDYLILCrGRkVknzARGqFjQQQCwRIaqmcRKtz+sSlaIteFDWE1TjocVL6k/hFSHj7bAGxVRj/SVKac1IzMwwpwbo+tbS192L67RKa1DtixGje1B8Hslwo6UWjqNrBnKwZFgwDuywhXCJAIp98yZac9Is5FYD6gZzXi+Eyamq3Z5biDEt65IRXJ2bErWGz1zvqiu53ZbLNnysNfEZkxlTMh0KFH9UgtDP2O10KT9P/1l+Oye+dabSH4oDhz0aqe4N3vuFYSExqeLxposvGyGEBL5T0OBJxaTHxTMZxJp25IB6nIsJmtH9ovgtCadqJeMhTYIg8BC+hk8T/sqxgsI0RBGYs4DDKKEWwbOya9Dt003VPe2PO0sOeUctPZ9Phd/qXaKmZfZ3kIZuPG9FIY+IOJbXgU0cFfSMWfRpT0kZTPq4MTqCXh1YD+u1P6caKTh5ndon8rFA6cOYH1xKAUzDH87M3kGVv5cIx7cQ2Htb7ckpWcCwzbW1BtgC4GgLO3s2nIj84pFxSBxgvevgREpquyIiOM3LnjVRVesjQntk8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
